version: "3"
services:
  mongoDB:
    container_name: mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '27017:27017'

  # backend:
    # container_name: wx-backend
    # build:
      # context: . 
      # dockerfile: Dockerfile 
    # restart: always
    # links:
      # - redis:redis
      # - postgres:postgres
    # depends_on:
      # - postgres
    # volumes:
      # - ./data/static:/static
      # - ./data/logs:/logs
    # ports:
      # - "0.0.0.0:9000:8080"

