version: "3"
services:
  mongoDB:
    container_name: easyTrader-mongoDB
    image: mongo:latest
    restart: always
    volumes:
      - ./data/mongo:/data/db
    ports:
      - '27017:27017'

  backend:
    container_name: easyTrader-backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    links:
      - mongoDB:mongoDB
    depends_on:
      - mongoDB
    volumes:
      - ./data/logs:/logs
    ports:
      - "0.0.0.0:9000:8080"

